In [104]:

# Utilizado para la manipulación de directorios y rutas
import os

# Cálculo científico y vectorial para python
import numpy as np

# Libreria para graficos
from matplotlib import pyplot

# Modulo de optimizacion en scipy
from scipy import optimize

# le dice a matplotlib que incruste gráficos en el cuaderno
%matplotlib inline

import pandas as pd

#sklearn, para tareas de aprendizaje automatico
#utilizamos la funcion train_test_split del modulo model_selection
#Esta funcion se utiliza para dividir un conjunto de datos
# en dos subconjuntos, uno para entrenamiento y otro para prueba
from sklearn.model_selection import train_test_split

In [102]:
# Cargar los datasets CSV
df1 = pd.read_csv('Datasets_combinados/PRSA_Data_Aotizhongxin_20130301-20170228.csv')
df2 = pd.read_csv('Datasets_combinados/PRSA_Data_Changping_20130301-20170228.csv')
df3 = pd.read_csv('Datasets_combinados/PRSA_Data_Dingling_20130301-20170228.csv')
df4 = pd.read_csv('Datasets_combinados/PRSA_Data_Dongsi_20130301-20170228.csv')
df5 = pd.read_csv('Datasets_combinados/PRSA_Data_Guanyuan_20130301-20170228.csv')
df6 = pd.read_csv('Datasets_combinados/PRSA_Data_Gucheng_20130301-20170228.csv')
df7 = pd.read_csv('Datasets_combinados/PRSA_Data_Huairou_20130301-20170228.csv')
df8 = pd.read_csv('Datasets_combinados/PRSA_Data_Nongzhanguan_20130301-20170228.csv')
df9 = pd.read_csv('Datasets_combinados/PRSA_Data_Shunyi_20130301-20170228.csv')
df10 = pd.read_csv('Datasets_combinados/PRSA_Data_Tiantan_20130301-20170228.csv')
df11 = pd.read_csv('Datasets_combinados/PRSA_Data_Wanliu_20130301-20170228.csv')
df12 = pd.read_csv('Datasets_combinados/PRSA_Data_Wanshouxigong_20130301-20170228.csv')

# Concatenar los datasets
merged_df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12])

# Mostrar el resultado
print(merged_df)

# Guardar el resultado en un nuevo archivo CSV
merged_df.to_csv('Air_D1.csv', index=False)

          No  year  month  day  hour  PM2.5  PM10   SO2   NO2     CO    O3  \
0          1  2013      3    1     0    4.0   4.0   4.0   7.0  300.0  77.0
1          2  2013      3    1     1    8.0   8.0   4.0   7.0  300.0  77.0
2          3  2013      3    1     2    7.0   7.0   5.0  10.0  300.0  73.0
3          4  2013      3    1     3    6.0   6.0  11.0  11.0  300.0  72.0
4          5  2013      3    1     4    3.0   3.0  12.0  12.0  300.0  72.0
...      ...   ...    ...  ...   ...    ...   ...   ...   ...    ...   ...
35059  35060  2017      2   28    19   11.0  32.0   3.0  24.0  400.0  72.0
35060  35061  2017      2   28    20   13.0  32.0   3.0  41.0  500.0  50.0
35061  35062  2017      2   28    21   14.0  28.0   4.0  38.0  500.0  54.0
35062  35063  2017      2   28    22   12.0  23.0   4.0  30.0  400.0  59.0
35063  35064  2017      2   28    23   13.0  19.0   4.0  38.0  600.0  49.0

       TEMP    PRES  DEWP  RAIN   wd  WSPM        station
0      -0.7  1023.0 -18.8   0.0  NNW   4.4   Aotizhongxin
1      -1.1  1023.2 -18.2   0.0    N   4.7   Aotizhongxin
2      -1.1  1023.5 -18.2   0.0  NNW   5.6   Aotizhongxin
3      -1.4  1024.5 -19.4   0.0   NW   3.1   Aotizhongxin
4      -2.0  1025.2 -19.5   0.0    N   2.0   Aotizhongxin
...     ...     ...   ...   ...  ...   ...            ...
35059  12.5  1013.5 -16.2   0.0   NW   2.4  Wanshouxigong
35060  11.6  1013.6 -15.1   0.0  WNW   0.9  Wanshouxigong
35061  10.8  1014.2 -13.3   0.0   NW   1.1  Wanshouxigong
35062  10.5  1014.4 -12.9   0.0  NNW   1.2  Wanshouxigong
35063   8.6  1014.1 -15.9   0.0  NNE   1.3  Wanshouxigong

[420768 rows x 18 columns]

In [105]:
# Leemos el dataset
data = pd.read_csv('Air_D1.csv')
# Mostramos el dataset
display(data)

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin
1,2,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin
2,3,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin
3,4,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin
4,5,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420763,35060,2017,2,28,19,11.0,32.0,3.0,24.0,400.0,72.0,12.5,1013.5,-16.2,0.0,NW,2.4,Wanshouxigong
420764,35061,2017,2,28,20,13.0,32.0,3.0,41.0,500.0,50.0,11.6,1013.6,-15.1,0.0,WNW,0.9,Wanshouxigong
420765,35062,2017,2,28,21,14.0,28.0,4.0,38.0,500.0,54.0,10.8,1014.2,-13.3,0.0,NW,1.1,Wanshouxigong
420766,35063,2017,2,28,22,12.0,23.0,4.0,30.0,400.0,59.0,10.5,1014.4,-12.9,0.0,NNW,1.2,Wanshouxigong
420767,35064,2017,2,28,23,13.0,19.0,4.0,38.0,600.0,49.0,8.6,1014.1,-15.9,0.0,NNE,1.3,Wanshouxigong

In [106]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420768 entries, 0 to 420767
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   No       420768 non-null  int64
 1   year     420768 non-null  int64
 2   month    420768 non-null  int64
 3   day      420768 non-null  int64
 4   hour     420768 non-null  int64
 5   PM2.5    412029 non-null  float64
 6   PM10     414319 non-null  float64
 7   SO2      411747 non-null  float64
 8   NO2      408652 non-null  float64
 9   CO       400067 non-null  float64
 10  O3       407491 non-null  float64
 11  TEMP     420370 non-null  float64
 12  PRES     420375 non-null  float64
 13  DEWP     420365 non-null  float64
 14  RAIN     420378 non-null  float64
 15  wd       418946 non-null  object
 16  WSPM     420450 non-null  float64
 17  station  420768 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 57.8+ MB

In [107]:
from sklearn.preprocessing import LabelEncoder
#Transformacion de columnas categoricas a numericas
#selecciona las columnas del dataset de tipo object
columnas_categoricas = data.select_dtypes(include=['object']).columns
#El for recorrera cada columna categorica
for columna in columnas_categoricas:
  #El LabelEncoder se utiliza para codificar las etiquetas categóricas como valores numéricos
  le = LabelEncoder()
  #aplica la transformación a la columna actual
  #El método fit_transform del LabelEncoder ajusta el codificador a los datos de la columna
  # y transforma las etiquetas categóricas en valores numéricos
  data[columna] = le.fit_transform(data[columna])

In [108]:
data.fillna(data.mean(), inplace=True)
data = data.drop(['No'], axis=1)

In [109]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420768 entries, 0 to 420767
Data columns (total 17 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   year     420768 non-null  int64
 1   month    420768 non-null  int64
 2   day      420768 non-null  int64
 3   hour     420768 non-null  int64
 4   PM2.5    420768 non-null  float64
 5   PM10     420768 non-null  float64
 6   SO2      420768 non-null  float64
 7   NO2      420768 non-null  float64
 8   CO       420768 non-null  float64
 9   O3       420768 non-null  float64
 10  TEMP     420768 non-null  float64
 11  PRES     420768 non-null  float64
 12  DEWP     420768 non-null  float64
 13  RAIN     420768 non-null  float64
 14  wd       420768 non-null  int32
 15  WSPM     420768 non-null  float64
 16  station  420768 non-null  int32
dtypes: float64(11), int32(2), int64(4)
memory usage: 51.4 MB

In [110]:
display(data)

,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,6,4.4,0
1,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,3,4.7,0
2,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,6,5.6,0
3,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,7,3.1,0
4,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,3,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420763,2017,2,28,19,11.0,32.0,3.0,24.0,400.0,72.0,12.5,1013.5,-16.2,0.0,7,2.4,11
420764,2017,2,28,20,13.0,32.0,3.0,41.0,500.0,50.0,11.6,1013.6,-15.1,0.0,14,0.9,11
420765,2017,2,28,21,14.0,28.0,4.0,38.0,500.0,54.0,10.8,1014.2,-13.3,0.0,7,1.1,11
420766,2017,2,28,22,12.0,23.0,4.0,30.0,400.0,59.0,10.5,1014.4,-12.9,0.0,6,1.2,11
420767,2017,2,28,23,13.0,19.0,4.0,38.0,600.0,49.0,8.6,1014.1,-15.9,0.0,5,1.3,11

In [111]:
valores_unicos = data['station'].unique()
print(valores_unicos)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [112]:
# Inicializamos el valor de num_labels en 3 porque y tiene 3 clases
num_labels = 12
# Asignamos las columnas a X y y
X = data.iloc[:, :16]
y = data.iloc[:, 16]
# Aisgnamos el valor de m con la cantidad de filas que hay en y
m = y.size

In [113]:
# Imprimimos X
print(X)

        year  month  day  hour  PM2.5  PM10   SO2   NO2     CO    O3  TEMP  \
0       2013      3    1     0    4.0   4.0   4.0   7.0  300.0  77.0  -0.7
1       2013      3    1     1    8.0   8.0   4.0   7.0  300.0  77.0  -1.1
2       2013      3    1     2    7.0   7.0   5.0  10.0  300.0  73.0  -1.1
3       2013      3    1     3    6.0   6.0  11.0  11.0  300.0  72.0  -1.4
4       2013      3    1     4    3.0   3.0  12.0  12.0  300.0  72.0  -2.0
...      ...    ...  ...   ...    ...   ...   ...   ...    ...   ...   ...
420763  2017      2   28    19   11.0  32.0   3.0  24.0  400.0  72.0  12.5
420764  2017      2   28    20   13.0  32.0   3.0  41.0  500.0  50.0  11.6
420765  2017      2   28    21   14.0  28.0   4.0  38.0  500.0  54.0  10.8
420766  2017      2   28    22   12.0  23.0   4.0  30.0  400.0  59.0  10.5
420767  2017      2   28    23   13.0  19.0   4.0  38.0  600.0  49.0   8.6

          PRES  DEWP  RAIN  wd  WSPM
0       1023.0 -18.8   0.0   6   4.4
1       1023.2 -18.2   0.0   3   4.7
2       1023.5 -18.2   0.0   6   5.6
3       1024.5 -19.4   0.0   7   3.1
4       1025.2 -19.5   0.0   3   2.0
...        ...   ...   ...  ..   ...
420763  1013.5 -16.2   0.0   7   2.4
420764  1013.6 -15.1   0.0  14   0.9
420765  1014.2 -13.3   0.0   7   1.1
420766  1014.4 -12.9   0.0   6   1.2
420767  1014.1 -15.9   0.0   5   1.3

[420768 rows x 16 columns]

In [114]:
# Imprimimos y
print(y)

0          0
1          0
2          0
3          0
4          0
          ..
420763    11
420764    11
420765    11
420766    11
420767    11
Name: station, Length: 420768, dtype: int32

In [115]:
def  featureNormalize(X): # define una función llamada featureNormalize que toma una matriz X como argumento de entrada
    X_norm = X.copy() # se crea una copia de la matriz de entrada X llamada X_norm
    # Se crean dos matrices mu y sigma, cada una con un tamaño igual al número de columnas de X
    mu = np.zeros(X.shape[1]) 
    sigma = np.zeros(X.shape[1])

    # Aquí se calculan las medias y desviaciones estándar de cada columna de X utilizando las funciones np.mean y np.std de NumPy
    # El argumento axis=0 indica que los cálculos deben realizarse a lo largo de las columnas
    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma # se realiza la normalización de características

    return X_norm, mu, sigma # la funcion devuelve tres valores: X_norm, mu, sigma

In [116]:
# llamamos a la funcion featureNormalize, enviando como parametro X
# que nos devuelve los valores de X_norm, mu, sigma
X_norm, mu, sigma = featureNormalize(X)

In [117]:
# se asignan los valores del número de filas (m) y el número de columnas (n)
# de la matriz X a las variables m y n, respectivamente
m, n = X_norm.shape
X = X_norm # la variable X se actualiza y se le asigna la matriz X_norm

In [118]:
# se calcula la función sigmoide de z
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

In [119]:
def lrCostFunction(theta, X, y, lambda_): #define una función llamada lrCostFunction que toma cuatro argumentos 
    # theta: es el vector de parametros del modelo
    # lambda_: Es el parametro de regularizacion
    m = y.size # asignamos a m la cantidad de filas que tiene y

    # θ es un conjunto de valores que se utilizan para predecir la salida de la función logística dada una entrada.
    
    # verifica si el tipo de datos de y es booleano. Si es así, se convierte
    # a tipo entero mediante el método astype(int) de NumPy
    if y.dtype == bool:
        y = y.astype(int)

    # Se inicializan las variables J(costo) y grad con valores iniciales de cero
    J = 0
    grad = np.zeros(theta.shape)

    # Aquí se calcula la hipótesis del modelo, h, aplicando la función sigmoide
    h = sigmoid(X.dot(theta.T))

    # Se crea una copia de los parámetros theta llamada temp. Luego, se establece el primer elemento de temp en cero
    temp = theta
    temp[0] = 0

    # Esta línea calcula el costo J
    # Es una medida de cuán bien está funcionando el modelo de regresión logística en los datos de entrenamiento
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h))) + (lambda_ / (2 * m)) * np.sum(np.square(temp))

    # el gradiente se utiliza en el proceso de optimización (por ejemplo, el descenso de gradiente) para actualizar los
    # parámetros θ en cada iteración del algoritmo de entrenamiento
    # El primer término calcula el gradiente sin regularización, mientras que el segundo término aplica la regularización
    grad = (1 / m) * (h - y).dot(X)
    grad = grad + (lambda_ / m) * temp

    return J, grad

In [120]:
def oneVsAll(X, y, num_labels, lambda_):
    # m igual a filas de X, n igual a las columnas de X
    m, n = X.shape

    # Se crea una matriz all_theta de tamaño (num_labels, n + 1) con valores iniciales de cero
    all_theta = np.zeros((num_labels, n + 1)) # matriz de puro ceros, num_labels 7 filas, n+1 columnas

    # Aquí se agrega una columna de unos a la matriz X
    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    # Este bucle itera sobre las etiquetas de clase
    for c in np.arange(num_labels):
        # Dentro del bucle, se inicializan los parámetros initial_theta con ceros
        initial_theta = np.zeros(n + 1)
        options = {'maxiter': 50}
        # se utiliza la función optimize.minimize de SciPy para minimizar la función de costo lrCostFunction
        # Se proporcionan los argumentos X, (y == c) (que crea un vector de booleanos que indica si
        # cada muestra pertenece a la clase c o no), lambda_, jac=True para indicar que se proporcionará
        # el gradiente en lrCostFunction, method='CG' para utilizar el método de optimización de gradiente
        # conjugado, y options para configurar el número máximo de iteraciones en 50.
        res = optimize.minimize(lrCostFunction,initial_theta,(X, (y == c), lambda_),jac=True,method='CG',options=options)
        # Se asigna el vector de parámetros óptimos res.x a la fila c de la matriz all_theta.
        all_theta[c] = res.x
    return all_theta

In [121]:
# asignamos a lambda_ el valor de 0.1
lambda_ = 0.1
# llamamos a la funcion oneVsAll para obtener all_theta
all_theta = oneVsAll(X, y, num_labels, lambda_)
print(all_theta.shape) #filas y columnas

(12, 17)

In [122]:
# imprimimos los valores de all_theta
print(all_theta)

[[-2.48785330e+00  9.05555022e-03 -7.15899383e-02 -2.65575520e-02
  -5.05114724e-02 -2.50999192e-01  1.71774466e-02  4.61166580e-02
   6.00504034e-01 -2.05636606e-01  2.30847598e-01 -2.91519502e-02
   4.57083567e-01  4.56653757e-01  8.55303627e-03 -6.12561514e-02
   1.55751842e-01]
 [-2.57783317e+00  9.33421150e-02  2.01496847e-01  5.85916861e-02
   6.48402867e-02  1.34578277e-01 -1.95191324e-01  6.70892147e-02
  -3.04171501e-01  1.28487617e-01 -1.51584517e-01 -3.35994539e-01
  -1.10781795e+00 -5.95927604e-01 -2.31653936e-02 -9.37172706e-02
   5.09312826e-03]
 [-3.08105897e+00  6.82006120e-02  2.52160395e-01  5.62327006e-02
   1.57048697e-01  7.42584030e-01 -1.97018183e-01  1.73561616e-01
  -1.85511954e+00  5.83335095e-02 -1.29185293e-01 -7.16673529e-01
  -1.11411613e+00 -4.97990071e-01 -6.36798760e-02 -1.23308071e-01
  -2.52233748e-01]
 [-2.48515902e+00 -2.11843623e-02 -7.69884911e-02 -2.19770833e-02
  -4.40787712e-02  3.28627954e-02 -2.87459011e-02  1.10144068e-01
   9.84727779e-02  3.68683026e-02 -4.62038077e-03  5.18756157e-01
   7.01688524e-01  2.12352701e-01  8.21502676e-03 -1.40780586e-01
   2.04053464e-01]
 [-2.46808125e+00  8.90593250e-03 -7.31732391e-02 -2.38780533e-02
  -3.72293075e-02 -1.83951436e-01 -1.49915499e-02  7.38040607e-02
   4.78001215e-01 -1.59730378e-01  1.59870037e-01  2.65961363e-02
   4.53945082e-01  4.31321161e-01  6.83153686e-03 -5.61945956e-02
   1.39241286e-01]
 [-2.58630949e+00  6.72700514e-02  9.42588796e-02  1.04699993e-02
  -3.85858553e-02 -3.49379939e-01  3.73759505e-01 -1.90725255e-01
   1.26807048e-01  9.03077710e-02  1.35761794e-01  2.02913035e-01
  -5.36404481e-01 -7.96009274e-01  3.74125912e-02  1.33215656e-01
  -7.00349787e-01]
 [-3.00416521e+00  7.45539139e-02  1.82502560e-01  4.61472624e-02
   2.39032096e-01  2.72702492e-01  1.03500099e-01  7.99200088e-02
  -1.50868401e+00  4.75994772e-02 -1.72763625e-01 -1.48672264e+00
  -1.31317350e+00  8.66526548e-02 -8.00159416e-02  2.76141569e-01
  -3.00282258e-01]
 [-2.52885538e+00 -1.08226566e-02 -6.66807638e-02 -2.30799070e-02
  -8.54480900e-02 -5.40638628e-02 -2.00567146e-01  8.42565848e-02
   5.53614100e-01 -3.19993637e-02  2.12824162e-01  3.94899099e-01
   6.82239150e-01  2.72401073e-01  1.11976404e-02 -1.53957971e-01
   2.79349638e-01]
 [-2.55685797e+00 -1.17423310e-01 -1.99050228e-01 -2.16149938e-02
   3.96559630e-02  3.34505538e-01 -3.58379431e-02 -1.19828076e-01
  -6.21934273e-01  1.37044934e-01 -3.17308217e-01  5.62460799e-01
   9.27646262e-01  3.03942712e-01 -8.25866550e-03  8.68222337e-02
   1.91732787e-02]
 [-2.49197095e+00 -1.09912241e-01 -1.62931428e-01 -1.99415275e-02
  -3.23288667e-02 -1.37137081e-02 -3.13990235e-02 -2.34623978e-01
   1.88734123e-01  1.64495883e-01 -9.31329895e-04  5.36290399e-01
   7.19581186e-01  1.46581777e-01  7.33643343e-03 -1.30540817e-01
   1.97437447e-01]
 [-2.53120282e+00  6.99852459e-02 -3.99003936e-02 -1.41336883e-02
  -3.10255106e-02 -2.78941726e-01 -1.79297166e-01  7.85408439e-02
   8.14784066e-01 -1.88615292e-01  1.38669193e-01  6.49777612e-03
   1.44232904e-01  2.19557783e-01  2.43033791e-02  5.15583950e-02
  -3.88143541e-02]
 [-2.44888768e+00 -1.73888699e-02 -7.15272998e-02 -1.39327129e-02
  -6.99443303e-02 -1.82215843e-01  5.72658037e-02 -2.74884343e-02
   1.81899056e-01  1.92428866e-01 -1.80649952e-02  3.71974455e-01
   3.87071452e-01  7.69236892e-02  1.51726870e-02  2.08654725e-01
   6.34633392e-02]]

In [123]:
def predictOneVsAll(all_theta, X):
    # Aquí se obtiene el número de muestras m de X y el número de clases num_labels del clasificador.
    m = X.shape[0];
    num_labels = all_theta.shape[0] # filas[0] y columnas[1]

    # Se crea un vector p de tamaño m inicializado con ceros
    p = np.zeros(m)

    # Aquí se agrega una columna de unos a la matriz X de las muestras
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    # Se calcula el producto de la matriz X y los parámetros all_theta transpuestos,
    # y se aplica la función sigmoide a la salida. Luego, se utiliza la función np.argmax
    # de NumPy para obtener el índice del valor máximo a lo largo del eje axis=1, que corresponde
    # a la clase con la mayor probabilidad para cada muestra. Estos índices se asignan al vector
    # p como las predicciones de clase.
    p = np.argmax(sigmoid(X.dot(all_theta.T)), axis = 1)
    return p

In [124]:
print(X.shape)

(420768, 16)

In [125]:
# Aquí se llama a la función predictOneVsAll para realizar la predicción de clases utilizando
# los parámetros all_theta y la matriz de características X
pred = predictOneVsAll(all_theta, X)
print('Precision del conjuto de entrenamiento: {:.2f}%'.format(np.mean(pred == y) * 100))
# Aquí se selecciona un subconjunto de las muestras de entrenamiento original X utilizando
# el índice de fila 10 a 149 (excluyendo la fila 150). Los datos se copian en la variable XPrueba.
XPrueba = X.iloc[400000:410000, :].copy()
# imprime la forma de la matriz XPrueba
print(XPrueba.shape)
# Aquí se agrega una columna de unos a la matriz XPrueba de las muestras de prueba
XPrueba = np.concatenate([np.ones((10000, 1)), XPrueba], axis=1)
print(XPrueba.shape)
# Se calcula la predicción de clase para las muestras de prueba en XPrueba. Se realiza
# la combinación lineal de las características y los parámetros utilizando el producto
# punto (dot) y se aplica la función sigmoide a la salida. Luego, se utiliza la función
# np.argmax para obtener el índice del valor máximo a lo largo del eje axis=1
# (es decir, la clase con la mayor probabilidad) para cada muestra de prueba.
# El resultado se asigna a la variable p.
p = np.argmax(sigmoid(XPrueba.dot(all_theta.T)), axis = 1)
print(p)
# Aquí se imprime el subconjunto correspondiente de las etiquetas de clase y para las muestras de prueba seleccionadas
# print(y[10:150])

Precision del conjuto de entrenamiento: 19.89%
(10000, 16)
(10000, 17)
[10  5  5 ...  8  8  9]